import { cronJobs } from "convex/server";
import { internal } from "./_generated/api";
const crons = cronJobs();
crons.interval("sync-apis-every-6-hours", { hours: 6 }, internal.actions.syncApiSources);
crons.interval("sync-rss-every-12-hours", { hours: 12 }, internal.actions.syncRssSources);
crons.interval("sync-scraping-every-24-hours", { hours: 24 }, internal.actions.syncScrapingSources);
crons.interval("validate-broken-links", { hours: 1 }, internal.actions.validateEventLinks);
crons.interval("expire-events-and-retain-logs", { hours: 1 }, internal.maintenance.expire);
crons.interval("archive-old-and-quarantined-events", { hours: 1 }, internal.maintenance.archive);
export default crons;
